### PR TITLE
Increased version number of debug library to get rid of NSP Warning about vulnerability in dependent ms library.

### PR DESCRIPTION
**Pull request by hulmgulm**
Hi,

I've increased the version number of "debug" library to get rid of NSP warning about a vulnerability in the "ms" library which is used by "debug".

It would be great if you could merge this.

Thank you.

### CODE REVIEW

**Comment by oskosk** [comment]
LGTM. Merging

**Comment by hulmgulm** [comment]
Thank you @oskosk for merging. Will you push these changes to npm repository too?

**Comment by oskosk** [comment]
Sure. On it

**Comment by oskosk** [comment]
Ok, it's up now!

**Pull request merged**
